OkulUI/Models/Ogrenci/OgrenciCreateModel.cs
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OkulUI.Models.Ogrenci
{
    public class OgrenciCreateModel
    {
        public Entities.Concrete.Ogrenci Ogrenci { get; set; }
        public List<Entities.Concrete.Ogretmen> Ogretmenler { get; set; }
        //public List<Bolum> Bolumler { get; set; }
    }
}

OkulUI/Models/Ogrenci/OgrenciListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.Concrete;
using Entities.Dtos;

namespace OkulUI.Models.Ogrenci
{
    public class OgrenciListModel
    {
        public List<OgrenciOgretmenDto> Ogrenciler { get; set; }
    }
}

OkulUI/Controllers/OgrenciController.cs
using Business.Abstract;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OkulUI.Models.Ogrenci;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OkulUI.Controllers
{
    public class OgrenciController : Controller
    {
        private readonly IOgrenciService _ogrenciService;
        private readonly IOgretmenService _ogretmenService;

        OkulContext _context;

        public OgrenciController(IOgrenciService ogrenciService, IOgretmenService ogretmenService)
        {
            _ogrenciService = ogrenciService;
            _ogretmenService = ogretmenService;
            _context = new OkulContext();
        }

        public IActionResult GetAll()
        {
            var model = new OgrenciListModel
            {
                Ogrenciler = _ogrenciService.GetOgrenciOgretmen().Data
            };

            return View(model);
        }

        public IActionResult Create()
        {
            List<SelectListItem> ogretmenler = (from ogr in _context.Ogretmenler.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = ogr.Ad + " " + ogr.Soyad,
                                                    Value = ogr.Id.ToString()
                                                }

                                                ).ToList();
            ViewBag.Ogretmenler = ogretmenler;

            List<SelectListItem> bolumler = (from bolum in _context.Bolumler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = bolum.BolumAd,
                                                 Value = bolum.Id.ToString()
                                             }

                                                ).ToList();
            ViewBag.Bolumler = bolumler;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Ogrenci ogrenci)
        {
            var model = new OgrenciCreateModel
            {
                Ogrenci = ogrenci
            };
            var result = _ogrenciService.Add(model.Ogrenci);
            if (result.Success)
            {
                return RedirectToAction("GetAll");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Update(int ogrenciId)
        {
            var ogrenci = _ogrenciService.GetById(ogrenciId).Data;

            List<SelectListItem> ogretmenler = (from ogr in _context.Ogretmenler.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = ogr.Ad + " " + ogr.Soyad,
                                                    Value = ogr.Id.ToString()
                                                }

                                                ).ToList();
            ViewBag.Ogretmenler = ogretmenler;

            List<SelectListItem> bolumler = (from bolum in _context.Bolumler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = bolum.BolumAd,
                                                 Value = bolum.Id.ToString()
                                             }

                                                ).ToList();
            ViewBag.Bolumler = bolumler;

            return View(ogrenci);
        }

        [HttpPost]
        public IActionResult Update(Ogrenci ogrenci)
        {
            var model = new OgrenciCreateModel
            {
                Ogrenci = ogrenci
            };
            var result = _ogrenciService.Update(model.Ogrenci);
            if (result.Success)
            {
                return RedirectToAction("GetAll");
            }
            return View();
        }

        public IActionResult Delete(int ogrenciId)
        {
            var ogrenci = _ogrenciService.GetById(ogrenciId).Data;
            var result = _ogrenciService.Delete(ogrenci);
            if (result.Success)
            {
                return RedirectToAction("GetAll");
            }
            return View();
        }

    }
}

OkulUI/Views/Ogrenci/Create.cshtml
@model OgrenciCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Öğrenci Ekle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Ogrenci" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Öğretmen Adı</label>
                @Html.DropDownListFor(m => m.Ogrenci.OgretmenId, (List<SelectListItem>)ViewBag.Ogretmenler, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label class="control-label">Bölüm Adı</label>
                @Html.DropDownListFor(m => m.Ogrenci.BolumId, (List<SelectListItem>)ViewBag.Bolumler, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label asp-for="Ogrenci.Ad" class="control-label"></label>
                <input asp-for="Ogrenci.Ad" class="form-control" />
                <span asp-validation-for="Ogrenci.Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ogrenci.Soyad" class="control-label"></label>
                <input asp-for="Ogrenci.Soyad" class="form-control" />
                <span asp-validation-for="Ogrenci.Soyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ogrenci.DogumTarihi" class="control-label"></label>
                <input type="date" asp-for="Ogrenci.DogumTarihi" class="form-control" />
                <span asp-validation-for="Ogrenci.DogumTarihi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ogrenci.Cinsiyet" class="control-label"></label>
                <input asp-for="Ogrenci.Cinsiyet" class="form-control" />
                <span asp-validation-for="Ogrenci.Cinsiyet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="GetAll">Geri Dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OkulUI/Views/Ogrenci/GetAll.cshtml
@model OgrenciListModel

@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a class="btn btn-info" asp-action="Create" asp-controller="Ogrenci">Öğrenci Ekle</a>
<p align="right" position: absolute; width: 300px;>Öğrenci: @Model.Ogrenciler.Count</p>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Öğrenci Adı</th>
            <th> Ögrenci Soyadı</th>
            <th>Ögrenci Yaş</th>
            <th>Ögrenci Cinsiyet</th>
            <th>Ögretmen Ad</th>
            <th>Ögretmen Soyadı</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    @{int i = 0; }
    <tbody>
        @foreach (var item in Model.Ogrenciler)
        {
            <tr>
                <td>
                    @{i += 1;} @i
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OgrenciAd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OgrenciSoyad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OgrenciYas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OgrenciCinsiyet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OgretmenAd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OgretmenSoyad)
                </td>
                <td>
                    <a href="/Ogrenci/Update/?OgrenciId=@item.OgrenciId" class="btn btn-success">Güncelle</a>
                    <a href="/Ogrenci/Delete/?OgrenciId=@item.OgrenciId" class="btn btn-danger">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

OkulUI/Views/Ogrenci/Update.cshtml
@model Ogrenci

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Ogrenci Güncelle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Öğretmen Adı</label>
                @Html.DropDownListFor(m => m.OgretmenId, (List<SelectListItem>)ViewBag.Ogretmenler, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label class="control-label">Bölüm Adı</label>
                @Html.DropDownListFor(m => m.BolumId, (List<SelectListItem>)ViewBag.Bolumler, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soyad" class="control-label"></label>
                <input asp-for="Soyad" class="form-control" />
                <span asp-validation-for="Soyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DogumTarihi" class="control-label"></label>
                <input type="date" asp-for="DogumTarihi" class="form-control" />
                <span asp-validation-for="DogumTarihi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cinsiyet" class="control-label"></label>
                <input asp-for="Cinsiyet" class="form-control" />
                <span asp-validation-for="Cinsiyet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="GetAll">Geri Dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}